import Head from 'next/head';
import React from 'react';
import Navbar from './Navbar';
import Footer from './Footer';

const Layout = ({ children, title }) => (
  <>
    <Head>
      <title>{title ? ` AutoMaster - ${title}` : title}</title>
      <meta name="AutoMaster" content="Generated by create-next-app by JBLL" />
      <meta charSet="UTF-8" />
      <meta
        name="author"
        content="José Antonio de Carvalho Bueno Barreira Motta"
      />
      <meta name="author" content="Luiz Gustavo Duarte Chagas" />
      <meta name="author" content="Lucas Felipe da Silva Nunes" />
      <meta name="author" content="Barbara dos Santos Mingatos" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/next.svg" />
    </Head>
    <div className="flex min-h-screen flex-col justify-between">
      <header>
        <Navbar />
      </header>
      <main>{children}</main>
      <footer>
        <Footer />
      </footer>
    </div>
  </>
);

export default Layout;
