import Head from 'next/head';
import React from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AdminNavbar from './AdminNavbar';

const AdminLayout = ({ children, title }) => (
  <>
    <Head>
      <title>{title ? ` AutoMaster - ${title}` : title}</title>
      <meta name="AutoMaster" content="Generated by create-next-app by JBLL" />
      <meta charSet="UTF-8" />
      <meta
        name="author"
        content="José Antonio de Carvalho Bueno Barreira Motta"
      />
      <meta name="author" content="Luiz Gustavo Duarte Chagas" />
      <meta name="author" content="Lucas Felipe da Silva Nunes" />
      <meta name="author" content="Barbara dos Santos Mingatos" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/next.svg" />
    </Head>
    <ToastContainer position="top-center" limit={1} />
    <div className="flex min-h-screen flex-col justify-between">
      <header className="mb-16">
        <AdminNavbar />
      </header>
      <main className="ml-40">{children}</main>
      <footer>footer</footer>
    </div>
  </>
);

export default AdminLayout;
