/* eslint-disable import/no-extraneous-dependencies */
import bcrypt from 'bcryptjs';

const data = {
  usersFast: [
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'Pedrão',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Pedrão2',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'usuario1@example.com',
      password: bcrypt.hashSync('teste'),
      isAdmin: false,
    },
  ],
  users: [
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'Pedrão',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Pedrão2',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'usuario1@example.com',
      password: bcrypt.hashSync('teste'),
      isAdmin: false,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Eliseo@gardner.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jayne_Kuhic@sydney.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Nikita@garfield.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lew@alysha.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Hayden@althea.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Presley.Mueller@myrl.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Dallas@ole.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Mallory_Kunze@marie.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Meghan_Littel@rene.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Carmen_Keeling@caroline.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Veronica_Goodwin@timmothy.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Oswald.Vandervort@leanne.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Kariane@jadyn.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Nathan@solon.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Maynard.Hodkiewicz@roberta.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Christine@ayana.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Preston_Hudson@blaise.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vincenza_Klocko@albertha.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Madelynn.Gorczany@darion.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Mariana_Orn@preston.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Noemie@marques.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Khalil@emile.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Sophia@arianna.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jeffery@juwan.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Isaias_Kuhic@jarrett.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Russel.Parker@kameron.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Francesco.Gleason@nella.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ronny@rosina.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jennings_Pouros@erica.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lurline@marvin.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Buford@shaylee.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Maria@laurel.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jaeden.Towne@arlene.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ethelyn.Schneider@emelia.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Georgianna@florence.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Raheem_Heaney@gretchen.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jacky@victoria.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Piper@linwood.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gaylord@russell.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Clare.Aufderhar@nicole.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lucio@gladys.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Shemar@ewell.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jackeline@eva.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Marianna_Wilkinson@rupert.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Marcia@name.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jeremy.Harann@waino.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Pearlie.Kling@sandy.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Manuela_Stehr@chelsie.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Camryn.Weimann@doris.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Kiana_Predovic@yasmin.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Laurie@lincoln.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Abigail.OConnell@june.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Laverne_Price@scotty.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Kenton_Vandervort@friedrich.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Hayden_Olson@marianna.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vince_Crist@heidi.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Darron.Nikolaus@eulah.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ezra_Abshire@lyda.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jameson@tony.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Americo@estrella.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Aurelio.Pfeffer@griffin.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vesta_Crooks@dora.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Margarett_Klein@mike.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Freida@brandt.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Mollie@agustina.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Janice@alda.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Dashawn@garry.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Devan.Nader@ettie.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Joana.Schoen@leora.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Minerva.Anderson@devonte.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lavinia@lafayette.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Sabrina.Marks@savanah.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Desmond_Graham@kailee.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gussie_Kunde@sharon.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Richard@chelsie.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gage_Turner@halle.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alfred@sadye.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Catharine@jordyn.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Esther_Ratke@shayna.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Evangeline@chad.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Newton.Kertzmann@anjali.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Caleb_Herzog@rosamond.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Sage_Mueller@candace.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Bernie.Bergnaum@lue.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alexzander_Davis@eduardo.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jacquelyn@krista.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Grover_Volkman@coty.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jovanny@abigale.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Isac_Schmeler@barton.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Sandy.Erdman@sabina.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alexandro@garry.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vickie_Schuster@harley.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Roma_Doyle@alia.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Tatum_Marks@jaylon.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Juston.Ruecker@scot.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "River.Grady@lavada.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Claudia@emilia.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Torrey@june.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Hildegard.Aufderhar@howard.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Leone_Fay@orrin.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lura@rod.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lottie.Zieme@ruben.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Winona_Price@jevon.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gabriel@oceane.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Adolph.Ondricka@mozell.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Allen@richard.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Nicholaus@mikayla.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Kayla@susanna.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gideon@amina.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cassidy@maribel.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Stefan.Crist@duane.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Aniyah.Ortiz@monte.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Laverna@rico.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Derek@hildegard.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Tyrell@abdullah.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Reyes@hailey.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Danika.Dicki@mekhi.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alessandra.Nitzsche@stephania.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Matteo@marquis.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Joshua.Spinka@toby.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Annabelle@cole.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Kacey@jamal.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Mina@mallie.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Hudson.Blick@ruben.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Domenic.Durgan@joaquin.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alexie@alayna.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Haven_Barrows@brant.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Marianne@maximo.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Fanny@danial.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Trevion_Kuphal@bernice.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Emmet@guy.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Megane.Fritsch@claude.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Amya@durward.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jasen_Rempel@willis.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Harmony@reggie.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Rosanna_Kunze@guy.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ressie.Boehm@flossie.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Domenic.Wuckert@jazmyne.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Rhett.OKon@brian.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Mathias@richmond.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ottis@lourdes.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Estel@newton.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Bertha@erik.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Joesph@matteo.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alva@cassandre.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vivienne@willis.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Angelita@aliza.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Timmothy_Okuneva@alyce.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Moriah_Welch@richmond.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ramiro_Kuhn@harmon.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cary@taurean.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Tillman_Koelpin@luisa.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Aleen@tania.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Durward@cindy.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lester@chauncey.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Telly_Lynch@karl.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Makenzie@libbie.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Amiya@perry.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Meghan@akeem.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Mitchel.Williamson@fletcher.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ashlee_Jast@emie.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Antwan@lori.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Estelle@valentina.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Haylie@gino.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Blake_Spinka@robyn.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Aimee.Bins@braeden.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Eloy@vladimir.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gabrielle@jada.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lee@dawn.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gideon.Hyatt@jalen.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Gerda.Reynolds@ceasar.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ivah@brianne.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ethyl_Bogan@candace.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Janelle_Guann@americo.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alfonzo.Barton@kelley.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Esther@ford.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Naomie_Cronin@rick.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Darryl@reginald.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Thea@aurelio.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Carolyn@eloisa.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Milan.Schoen@cortney.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Sabrina@raymond.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Hildegard@alford.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lowell.Pagac@omari.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vivianne@ima.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Yasmin.Prohaska@hanna.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ursula.Kirlin@eino.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Nichole_Bartoletti@mozell.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lottie_Wyman@jasen.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Dominique_Hermann@paige.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Eugene@mohammed.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Janick@marty.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alena@deron.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Alphonso_Rosenbaum@valentin.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Frank@rosalind.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jenifer_Lowe@reuben.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cecelia_Nitzsche@marty.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Christop_Friesen@jordan.me",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cooper_Boehm@damian.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Amir@kaitlyn.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cleve@royal.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Donnell@polly.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Bonita@karl.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Shea@angelina.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Omari@veronica.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Sophie@antoinette.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jessika@crystel.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cesar_Volkman@letitia.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Maureen_Mueller@lance.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Eriberto@geovany.ca",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Faustino.Keeling@morris.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Viola@aric.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Felton_Huel@terrell.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ferne_Bogan@angus.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Amy@reymundo.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jaylan.Mayert@norbert.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cristina.DAmore@destini.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Ettie_Bashirian@lambert.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lizeth@kellen.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Vladimir_Schumm@sharon.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Madonna@will.com",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cicero_Goldner@elenor.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Zella@jan.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Robin_Jacobi@verdie.net",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Lawson@demarco.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Benton@jayde.tv",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Melody@london.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Wyman.Swaniawski@marjorie.name",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Deborah@fletcher.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Dario@barton.info",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Kelton_McKenzie@danial.us",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Itzel@fritz.io",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Jacquelyn_Kutch@kaya.co.uk",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Cheyanne.Schowalter@alycia.biz",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: "Macey@abbie.org",
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
  ],
  cars: {
    owner: '64ab0f9ccaca93336f866bac',
    image: 'image',
    brand: 'BMW',
    model: 'X5',
    fueltype: 'Gasolina',
    hodometro: 1000,
    color: 'Verde',
    type: 3,
    year: '2017',
    licensePlate: 'ABC-1234',
    chassis: 'aaaa',
  },
  parts: {
    carId: '64b7c1b17583eff72e1197e3',
    title: 'farol',
    price: 5,
    options: [
      {
        title: 'Força da luz',
        value: '10',
      },
    ],
  },
  maintenances: {
    carId: '64b7c1b17583eff72e1197e3',
    partId: '64b56bfc3dad753214f0bb77',
    title: 'Troca do farol',
    subtitle: 'Troca do led do farol para neon',
    description: 'A troca deve ser feita na mecanica xuruta, com neon azul escuro',
    date: new Date('2023-07-19T10:32:48Z'),
    price: 55,
  },
  reviews: {
    carId: '64b7c1b17583eff72e1197e3',
    partId: '64b56bfc3dad753214f0bb77',
    total: false,
    title: 'Troca do farol',
    subtitle: 'Troca do led do farol para neon',
    description: 'A troca deve ser feita na mecanica xuruta, com neon azul escuro',
    date: new Date('2023-07-19T10:32:48Z'),
    price: 55,
  },
  refuels: {
    carId: '64b7c1b17583eff72e1197e3',
    title: 'Abastecido no posto do Ipiranga',
    type: 'Gasolina',
    description: 'Abastecimento de gasolina aditivada',
    quantity: 200,
    local: 'Posto Ipiranga da rua do OZE',
    date: new Date('2023-07-19T10:32:48Z'),
    price: 55,
  },
};
export default data;
