/* eslint-disable import/no-extraneous-dependencies */
import bcrypt from 'bcryptjs';

const data = {
  usersFast: [
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'Pedrão',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Pedrão2',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'usuario1@example.com',
      password: bcrypt.hashSync('teste'),
      isAdmin: false,
    },
  ],
  users: [
    {
      name: 'José',
      lastName: 'Antonio Motta',
      image: '/imgUser/admin.png',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'Pedrão',
      lastName: 'Do Carmo',
      image: '/imgUser/user.png',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Valdemir',
      lastName: 'Augusto',
      image: '/imgUser/user.png',
      email: 'usuario1@example.com',
      password: bcrypt.hashSync('teste'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Wilson',
      image: '/imgUser/admin.png',
      email: 'Daniel_Wilson@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Thompson',
      image: '/imgUser/admin.png',
      email: 'Matthew_Thompson@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Anderson',
      image: '/imgUser/admin.png',
      email: 'James_Anderson@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Harris',
      image: '/imgUser/admin.png',
      email: 'John_Harris@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Martin',
      image: '/imgUser/admin.png',
      email: 'Michael_Martin@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Jackson',
      image: '/imgUser/admin.png',
      email: 'David_Jackson@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'White',
      image: '/imgUser/admin.png',
      email: 'Robert_White@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Thompson',
      image: '/imgUser/admin.png',
      email: 'William_Thompson@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Lewis',
      image: '/imgUser/admin.png',
      email: 'Richard_Lewis@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Robinson',
      image: '/imgUser/admin.png',
      email: 'Charles_Robinson@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Walker',
      image: '/imgUser/admin.png',
      email: 'Joseph_Walker@timmothy.net',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Hill',
      image: '/imgUser/admin.png',
      email: 'Thomas_Hill@leanne.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Parker',
      image: '/imgUser/admin.png',
      email: 'Daniel_Parker@jadyn.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Edwards',
      image: '/imgUser/admin.png',
      email: 'Matthew_Edwards@solon.io',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Stewart',
      image: '/imgUser/admin.png',
      email: 'James_Stewart@roberta.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Phillips',
      image: '/imgUser/admin.png',
      email: 'John_Phillips@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Bennett',
      image: '/imgUser/admin.png',
      email: 'Michael_Bennett@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Ross',
      image: '/imgUser/admin.png',
      email: 'David_Ross@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Bell',
      image: '/imgUser/admin.png',
      email: 'Robert_Bell@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Powell',
      image: '/imgUser/admin.png',
      email: 'William_Powell@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Ward',
      image: '/imgUser/admin.png',
      email: 'Richard_Ward@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Turner',
      image: '/imgUser/admin.png',
      email: 'Charles_Turner@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Cox',
      image: '/imgUser/admin.png',
      email: 'Joseph_Cox@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Coleman',
      image: '/imgUser/admin.png',
      email: 'Thomas_Coleman@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Hayes',
      image: '/imgUser/admin.png',
      email: 'Daniel_Hayes@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Griffin',
      image: '/imgUser/admin.png',
      email: 'Matthew_Griffin@timmothy.net',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Dixon',
      image: '/imgUser/admin.png',
      email: 'James_Dixon@leanne.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Hunt',
      image: '/imgUser/admin.png',
      email: 'John_Hunt@jadyn.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Palmer',
      image: '/imgUser/admin.png',
      email: 'Michael_Palmer@solon.io',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Bryant',
      image: '/imgUser/admin.png',
      email: 'David_Bryant@roberta.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Barnes',
      image: '/imgUser/admin.png',
      email: 'Robert_Barnes@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Warren',
      image: '/imgUser/admin.png',
      email: 'William_Warren@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Jenkins',
      image: '/imgUser/admin.png',
      email: 'Richard_Jenkins@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Grant',
      image: '/imgUser/admin.png',
      email: 'Charles_Grant@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Knight',
      image: '/imgUser/admin.png',
      email: 'Joseph_Knight@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Snyder',
      image: '/imgUser/admin.png',
      email: 'Thomas_Snyder@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Holmes',
      image: '/imgUser/admin.png',
      email: 'Daniel_Holmes@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Porter',
      image: '/imgUser/admin.png',
      email: 'Matthew_Porter@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Banks',
      image: '/imgUser/admin.png',
      email: 'James_Banks@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Graham',
      image: '/imgUser/admin.png',
      email: 'John_Graham@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Pierce',
      image: '/imgUser/admin.png',
      email: 'Michael_Pierce@timmothy.net',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Murray',
      image: '/imgUser/admin.png',
      email: 'David_Murray@leanne.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Weaver',
      image: '/imgUser/admin.png',
      email: 'Robert_Weaver@jadyn.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Cole',
      image: '/imgUser/admin.png',
      email: 'William_Cole@solon.io',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Bishop',
      image: '/imgUser/admin.png',
      email: 'Richard_Bishop@roberta.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'McDonald',
      image: '/imgUser/admin.png',
      email: 'Charles_McDonald@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Grant',
      image: '/imgUser/admin.png',
      email: 'Joseph_Grant@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Carroll',
      image: '/imgUser/admin.png',
      email: 'Thomas_Carroll@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Campbell',
      image: '/imgUser/admin.png',
      email: 'Daniel_Campbell@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Meyer',
      image: '/imgUser/admin.png',
      email: 'Matthew_Meyer@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Ross',
      image: '/imgUser/admin.png',
      email: 'James_Ross@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Hamilton',
      image: '/imgUser/admin.png',
      email: 'John_Hamilton@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Reynolds',
      image: '/imgUser/admin.png',
      email: 'Michael_Reynolds@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Stevens',
      image: '/imgUser/admin.png',
      email: 'David_Stevens@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Simmons',
      image: '/imgUser/admin.png',
      email: 'Robert_Simmons@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Patterson',
      image: '/imgUser/admin.png',
      email: 'William_Patterson@timmothy.net',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Jordan',
      image: '/imgUser/admin.png',
      email: 'Richard_Jordan@leanne.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Gonzalez',
      image: '/imgUser/admin.png',
      email: 'Charles_Gonzalez@jadyn.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Fox',
      image: '/imgUser/admin.png',
      email: 'Joseph_Fox@solon.io',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Rice',
      image: '/imgUser/admin.png',
      email: 'Thomas_Rice@roberta.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Baldwin',
      image: '/imgUser/admin.png',
      email: 'Daniel_Baldwin@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Miles',
      image: '/imgUser/admin.png',
      email: 'Matthew_Miles@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'West',
      image: '/imgUser/admin.png',
      email: 'James_West@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Gomez',
      image: '/imgUser/admin.png',
      email: 'John_Gomez@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Burns',
      image: '/imgUser/admin.png',
      email: 'Michael_Burns@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Dean',
      image: '/imgUser/admin.png',
      email: 'David_Dean@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Harvey',
      image: '/imgUser/admin.png',
      email: 'Robert_Harvey@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Mills',
      image: '/imgUser/admin.png',
      email: 'William_Mills@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Hart',
      image: '/imgUser/admin.png',
      email: 'Richard_Hart@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Lane',
      image: '/imgUser/admin.png',
      email: 'Charles_Lane@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'George',
      image: '/imgUser/admin.png',
      email: 'Joseph_George@timmothy.net',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Palmer',
      image: '/imgUser/admin.png',
      email: 'Thomas_Palmer@leanne.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Wells',
      image: '/imgUser/admin.png',
      email: 'Daniel_Wells@jadyn.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Sullivan',
      image: '/imgUser/admin.png',
      email: 'Matthew_Sullivan@solon.io',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Wallace',
      image: '/imgUser/admin.png',
      email: 'James_Wallace@roberta.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Allen',
      image: '/imgUser/admin.png',
      email: 'John_Allen@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Sanchez',
      image: '/imgUser/admin.png',
      email: 'Michael_Sanchez@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Coleman',
      image: '/imgUser/admin.png',
      email: 'David_Coleman@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Marshall',
      image: '/imgUser/admin.png',
      email: 'Robert_Marshall@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Fields',
      image: '/imgUser/admin.png',
      email: 'William_Fields@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Castro',
      image: '/imgUser/admin.png',
      email: 'Richard_Castro@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Banks',
      image: '/imgUser/admin.png',
      email: 'Charles_Banks@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Delgado',
      image: '/imgUser/admin.png',
      email: 'Joseph_Delgado@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Howell',
      image: '/imgUser/admin.png',
      email: 'Thomas_Howell@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Baxter',
      image: '/imgUser/admin.png',
      email: 'Daniel_Baxter@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Banks',
      image: '/imgUser/admin.png',
      email: 'Matthew_Banks@timmothy.net',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Rivera',
      image: '/imgUser/admin.png',
      email: 'James_Rivera@leanne.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Valdez',
      image: '/imgUser/admin.png',
      email: 'John_Valdez@jadyn.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Michael',
      lastName: 'Parks',
      image: '/imgUser/admin.png',
      email: 'Michael_Parks@solon.io',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'David',
      lastName: 'Russell',
      image: '/imgUser/admin.png',
      email: 'David_Russell@roberta.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Robert',
      lastName: 'Fleming',
      image: '/imgUser/admin.png',
      email: 'Robert_Fleming@gardner.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'William',
      lastName: 'Gonzales',
      image: '/imgUser/admin.png',
      email: 'William_Gonzales@sydney.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Richard',
      lastName: 'Baldwin',
      image: '/imgUser/admin.png',
      email: 'Richard_Baldwin@garfield.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Charles',
      lastName: 'Farmer',
      image: '/imgUser/admin.png',
      email: 'Charles_Farmer@alysha.tv',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Joseph',
      lastName: 'Holland',
      image: '/imgUser/admin.png',
      email: 'Joseph_Holland@althea.biz',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Thomas',
      lastName: 'Hines',
      image: '/imgUser/admin.png',
      email: 'Thomas_Hines@myrl.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Daniel',
      lastName: 'Bishop',
      image: '/imgUser/admin.png',
      email: 'Daniel_Bishop@ole.me',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'Matthew',
      lastName: 'Hudson',
      image: '/imgUser/admin.png',
      email: 'Matthew_Hudson@marie.org',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'James',
      lastName: 'Mendez',
      image: '/imgUser/admin.png',
      email: 'James_Mendez@rene.us',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
    {
      name: 'John',
      lastName: 'Kent',
      image: '/imgUser/admin.png',
      email: 'John_Kent@caroline.name',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
  ],
  cars: {
    owner: '64ab0f9ccaca93336f866bac',
    image: 'image',
    brand: 'BMW',
    model: 'X5',
    fueltype: 'Gasolina',
    hodometro: 1000,
    color: 'Verde',
    type: 3,
    year: '2017',
    licensePlate: 'ABC-1234',
    chassis: 'aaaa',
  },
  parts: {
    carId: '64b7c1b17583eff72e1197e3',
    title: 'farol',
    price: 5,
    options: [
      {
        title: 'Força da luz',
        value: '10',
      },
    ],
  },
  maintenances: {
    carId: '64b7c1b17583eff72e1197e3',
    partId: '64b56bfc3dad753214f0bb77',
    title: 'Troca do farol',
    subtitle: 'Troca do led do farol para neon',
    description: 'A troca deve ser feita na mecanica xuruta, com neon azul escuro',
    date: new Date('2023-07-19T10:32:48Z'),
    price: 55,
  },
  reviews: {
    carId: '64b7c1b17583eff72e1197e3',
    partId: '64b56bfc3dad753214f0bb77',
    total: false,
    title: 'Troca do farol',
    subtitle: 'Troca do led do farol para neon',
    description: 'A troca deve ser feita na mecanica xuruta, com neon azul escuro',
    date: new Date('2023-07-19T10:32:48Z'),
    price: 55,
  },
  refuels: {
    carId: '64b7c1b17583eff72e1197e3',
    title: 'Abastecido no posto do Ipiranga',
    type: 'Gasolina',
    description: 'Abastecimento de gasolina aditivada',
    quantity: 200,
    local: 'Posto Ipiranga da rua do OZE',
    date: new Date('2023-07-19T10:32:48Z'),
    price: 55,
  },
};
export default data;
